### ISSUE TITLE
Remove shell command

### ISSUE THREAD

**Issue by MaT1g3R** [hifumibot/hifumibot#20]
It is too insecure and can kill the vps

**Comment by Underforest** [comment]
I didn't agree with the removing after reconsideration in Wolke's discussion. Will also explain this carefully in docs so don't worry~

**Comment by MaT1g3R** [comment]
Doing system administration through Discord is a terrible idea, please don't do it, re-opening

**Comment by Underforest** [comment]
After reconsideration, removed in commit 3b0f3dc
