### ISSUE TITLE
Errors related to server's fault shouldn't be sent to developer but to the channel

### ISSUE THREAD

**Issue by Underforest** [hifumibot/hifumibot#4]
What I mean is, if bot has not permissions or something wrong happened because one of the server settings, those errors shouldn't be sent because those are not important at all and it won't affect environment at all

Some examples:
`FORBIDDEN (status code: 403): Missing Access`
`NOT FOUND (status code: 404): Unknown Channel`
`ERROR (status code: 400) Bad Request`
`RATELIMITED (status code: 429) Too many requests`
etc.

**Comment by MaT1g3R** [comment]
fixed
