### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite integer 

### ISSUE THREAD

**Issue by ParadoxOrigins** [hifumibot/hifumibot#7]
![capture](https://user-images.githubusercontent.com/25114435/27334352-5d73ae96-55c9-11e7-8f53-ba771e812d87.PNG)

https://cdn.discordapp.com/attachments/227913600163905538/326706884373643264/6e728618e07641af2935e433ea185225.png

from now on imma open issues for every bugs reported on the discord, tell me if you dont want that

**Comment by MaT1g3R** [comment]
Fixed
