### ISSUE TITLE
NSFW commands returning errors 

### ISSUE THREAD

**Issue by ParadoxOrigins** [hifumibot/hifumibot#9]
:warning: I ran into an error while executing this command. Please report this to my developers.
Triggered message: ~yandere furies or whatever its just a test anyway
Type: CommandInvokeError
Exception: Command raised an exception: TypeError: init() missing 2 required positional arguments: 'request_info' and 'history'

Hifumi - Today at 21:04
:warning: I ran into an error while executing this command. Please report this to my developers.
Triggered message: ~e621 furies or whatever dunno
Type: CommandInvokeError
Exception: Command raised an exception: ClientConnectionError: Connection closed

Seems like errors like missing argument or when the search return no results are not handled, dunno if you already know about this but well

**Comment by MaT1g3R** [comment]
Fixed
